### ISSUE TITLE
tmpPath issue

### ISSUE THREAD

**Issue by ifduyue** [sapics/gulp-uglify-cli#1]
Hello,

First I want to thank you for writing this gulp plugin. It runs faster and saves ~5min compared to gulp-uglify for one of my projects. Really good work!

But there is a possible issue about tmpPath.

``` js
var pk = Date.now()

...

var tmpPath = path.normalize(opts.tmp ? opts.tmp
    : path.join(os.tmpdir(), 'uglify-' + (pk++).toString(36) + '.js'))
```

If two gulps run in the same time, it is possible that there is a tmpPath conflict, hence leading to an undesired output, or throwing an error complaining that file doesn't exist.
Better to make tmpPath more random. What's your thought?

**Comment by sapics** [comment]
Thank you for using this plugin. It's my pleasure!
I did not know that the plugin have an advantage in performance. I am glad to know it!

Absolutely, you are right.
I have not considered about running multiple gulps.
Now, I fix in https://github.com/sapics/gulp-uglify-cli/blob/master/index.js#L34.
It would be better randomness.
