### ISSUE TITLE
custom uglifyjs path

### ISSUE THREAD

**Issue by ifduyue** [sapics/gulp-uglify-cli#2]
Support custom uglifyjs path, for example ./node_modules/.bin/uglifyjs

I'm not good at Javascript things, but if you prefer, I can send a pull request.

**Comment by sapics** [comment]
Thank you for feature request.
That's good idea :+1: 
I fix it!

**Comment by ifduyue** [comment]
@sapics Thanks

In the README there is a typo `/home/node_nodules/.bin/uglifyjs`

**Comment by sapics** [comment]
Oops! Thanks!
